apiVersion: batch/v1
kind: CronJob
metadata:
  name: knada-ping
  namespace: knada-system
spec:
  schedule: 0 * * * *
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: knada-ping
            image: europe-north1-docker.pkg.dev/knada-gcp/knada-north/knada-ping
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: knada-ping
          restartPolicy: OnFailure
