apiVersion: batch/v1
kind: CronJob
metadata:
  name: knada-ping
  namespace: knada-system
spec:
  schedule: 0 * * * *
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: knada-ping
            image: europe-west1-docker.pkg.dev/knada-gcp/knada/knada-ping
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: github-read-token
          restartPolicy: OnFailure
